const images={industry:'https://merimp.com/wp-content/uploads/2024/03/banner_HP.jpg',people:'https://merimp.com/wp-content/uploads/2025/06/azienda.jpg',mission:'https://merimp.com/wp-content/uploads/elementor/thumbs/mission-rbg26ulk8inrke2dqyamqhpnxlnz4pqnfx4596hvjk.jpg',vision:'https://merimp.com/wp-content/uploads/elementor/thumbs/vision-rbg26ulk8inrke2dqyamqhpnxlnz4pqnfx4596hvjk.jpg'};
const base=[
 {cat:'VISIONE',msg:'Trasformiamo sistemi complessi in progresso concreto.',sub:'Innovazione e competenza al servizio di chi guarda al futuro.',icon:'◆',target:"Tutta l'azienda",image:images.industry},
 {cat:'PERSONE',msg:'Oltre 600 professionisti. Un’unica direzione: crescere insieme.',sub:'Ogni competenza rafforza il valore dell’intera squadra.',icon:'◎',target:"Tutta l'azienda",image:images.people},
 {cat:'SICUREZZA',msg:'Il lavoro migliore è quello che ci riporta a casa, ogni giorno.',sub:'La sicurezza è una responsabilità condivisa.',icon:'◇',target:'Cantieri',image:images.mission},
 {cat:'INNOVAZIONE',msg:'L’esperienza ci dà solide radici. La ricerca ci porta più lontano.',sub:'Curiosità, metodo e tecnologia trasformano le idee in soluzioni.',icon:'✦',target:'Uffici',image:images.vision},
 {cat:'QUALITÀ',msg:'L’eccellenza non è un episodio. È il modo in cui affrontiamo ogni dettaglio.',sub:'Precisione e affidabilità costruiscono fiducia.',icon:'✓',target:'Produzione',image:images.industry},
 {cat:'SQUADRA',msg:'Dalla progettazione alla manutenzione, il risultato parla di tutti noi.',sub:'Competenze diverse, responsabilità comune.',icon:'⊕',target:"Tutta l'azienda",image:images.people},
 {cat:'CRESCITA',msg:'Ogni problema risolto oggi diventa competenza per il progetto di domani.',sub:'Condividiamo ciò che impariamo.',icon:'↗',target:"Tutta l'azienda",image:images.vision},
 {cat:'SOSTENIBILITÀ',msg:'Innovare significa creare valore che duri nel tempo.',sub:'Tecnologia responsabile per industria, persone e territorio.',icon:'◌',target:"Tutta l'azienda",image:images.mission}
];
const slides=[...base,...JSON.parse(localStorage.getItem('mi-approved')||'[]')];let index=0,playing=true,seconds=15,duration=Number(localStorage.getItem('mi-duration')||15);const $=s=>document.querySelector(s);
function active(){const d=$('#department')?.value||"Tutta l'azienda";return slides.filter(s=>d==="Tutta l'azienda"||s.target===d||s.target==="Tutta l'azienda")}
function render(){const list=active();if(index>=list.length)index=0;const s=list[index];$('#category').textContent=s.cat;$('#message').textContent=s.msg;$('#submessage').textContent=s.sub;$('#screenDept').textContent=$('#department').value.toUpperCase();$('#slideNumber').textContent=String(index+1).padStart(2,'0')+' / '+String(list.length).padStart(2,'0');$('#timeline').style.width=((index+1)/list.length*100)+'%';const screen=$('#screen');screen.classList.add('has-image');screen.style.background=`center / cover url('${s.image||images.people}')`;seconds=duration;buildQueue()}
function buildQueue(){const list=active();$('#queue').innerHTML=[1,2,3].map(n=>{const s=list[(index+n)%list.length];return `<div class="queue-item"><span class="icon">${s.icon}</span><div><strong>${s.cat[0]+s.cat.slice(1).toLowerCase()}</strong><small>${s.msg.slice(0,47)}…</small></div><time>tra ${n*duration} sec</time></div>`}).join('')}
function next(){index=(index+1)%active().length;render()}function prev(){index=(index-1+active().length)%active().length;render()}function tick(){if(!playing)return;seconds--;$('#progress').style.width=((duration-seconds)/duration*100)+'%';if(seconds<=0)next()}
$('#next').onclick=next;$('#previous').onclick=prev;$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'Ⅱ':'▶'};$('#fullscreen').onclick=()=>{document.body.classList.add('tv-mode');document.documentElement.requestFullscreen?.()};document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('tv-mode')});document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev()});
const generators={Crescita:['Ogni sfida affrontata con metodo aumenta il valore della nostra esperienza.','Crescere significa trasformare ciò che impariamo in una possibilità per tutta la squadra.','Il prossimo miglioramento comincia da un dettaglio osservato con attenzione.'],Squadra:['Il risultato migliore nasce quando competenza, ascolto e responsabilità lavorano insieme.','Le persone fanno la differenza quando condividono obiettivi e soluzioni.','Una squadra forte non somma soltanto competenze: moltiplica possibilità.'],Sicurezza:['La sicurezza è parte del lavoro ben fatto, dal primo gesto all’ultimo controllo.','Proteggere noi stessi e i colleghi è il risultato più importante di ogni giornata.','La prevenzione nasce dall’attenzione: fermarsi, verificare, agire con consapevolezza.'],Innovazione:['La tecnologia diventa progresso quando risolve problemi reali con semplicità e precisione.','Ricerca e competenza trasformano una buona intuizione in una soluzione affidabile.','Innovare è un lavoro di squadra: osservare, sperimentare, misurare e migliorare.'],Risultati:['Ogni traguardo racconta il contributo di persone che hanno scelto la stessa direzione.','Un risultato condiviso vale due volte: celebra il presente e prepara il futuro.','La qualità del risultato nasce dalla qualità delle scelte fatte lungo il percorso.']};
let proposal=0;const getReviewer=()=>localStorage.getItem('mi-reviewer')||'Responsabile comunicazione interna';function syncReviewer(){if($('#reviewerPreview'))$('#reviewerPreview').textContent=getReviewer();if($('#approvalOwner'))$('#approvalOwner').textContent=getReviewer()}function generate(){const list=generators[$('#theme').value];proposal=(proposal+1)%list.length;$('#aiPreview').textContent=list[proposal]}$('#generate').onclick=()=>{proposal=Math.floor(Math.random()*3);generate();$('#target').value=$('#department').value;syncReviewer();$('#generator').showModal()};$('#theme').onchange=generate;$('#regenerate').onclick=generate;
let pending=JSON.parse(localStorage.getItem('mi-pending')||'null')||[{cat:'SQUADRA',msg:'La fiducia cresce quando ognuno porta competenza e ascolto nello stesso progetto.',sub:'Collaborazione',icon:'◎',target:"Tutta l'azienda",image:images.people},{cat:'INNOVAZIONE',msg:'Le soluzioni di domani iniziano dalle domande che abbiamo il coraggio di fare oggi.',sub:'Innovazione',icon:'✦',target:'Uffici',image:images.vision},{cat:'SICUREZZA',msg:'La sicurezza non rallenta il lavoro: protegge il futuro di tutti.',sub:'Sicurezza',icon:'◇',target:'Cantieri',image:images.mission}];
$('#publish').onclick=e=>{e.preventDefault();pending.push({cat:$('#theme').value.toUpperCase(),msg:$('#aiPreview').textContent,sub:'MI Inspire · Crescita condivisa',icon:'✦',target:$('#target').value,image:images.people,reviewer:getReviewer()});savePending();$('#generator').close();toast('Inserito nella coda di '+getReviewer())};function savePending(){localStorage.setItem('mi-pending',JSON.stringify(pending));$('#approvalBadge').textContent=pending.length;$('#approvalBadge').style.display=pending.length?'':'none';approvals()}
function approvals(){syncReviewer();const box=$('#approvalList');if(!pending.length){box.innerHTML='<div class="suggestion"><p>Tutto approvato. Il palinsesto è aggiornato.</p></div>';return}box.innerHTML=pending.map((p,i)=>`<article class="approval-card"><div class="approval-meta"><span>${p.cat} · trasmissione: ${p.target}</span><span>Approva: ${p.reviewer||getReviewer()}</span></div><p>${p.msg}</p><div class="approval-actions"><button type="button" class="approve" data-a="${i}">✓ Approva e pubblica</button><button type="button" data-r="${i}">Rifiuta</button></div></article>`).join('');box.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{slides.push(pending.splice(+b.dataset.a,1)[0]);localStorage.setItem('mi-approved',JSON.stringify(slides.slice(base.length)));savePending();render();toast('Contenuto approvato e in palinsesto')});box.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{pending.splice(+b.dataset.r,1);savePending();toast('Contenuto rimosso')})}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}const openApprovals=()=>{$('#approvals').showModal();approvals()};$('#contentNav').onclick=openApprovals;$('#manageQueue').onclick=openApprovals;$('#settingsNav').onclick=()=>{$('#duration').value=duration;$('#durationValue').textContent=duration+' secondi';$('#reviewer').value=getReviewer();$('#settings').showModal()};$('#scheduleNav').onclick=()=>toast(`Palinsesto attivo: ${active().length} contenuti per ${$('#department').value}`);$('#screensNav').onclick=()=>toast('TV Hall principale connessa e sincronizzata');$('#department').onchange=e=>{localStorage.setItem('mi-department',e.target.value);index=0;render();toast('Palinsesto impostato per: '+e.target.value)};$('#duration').oninput=e=>$('#durationValue').textContent=e.target.value+' secondi';$('#saveSettings').onclick=e=>{e.preventDefault();duration=Number($('#duration').value);localStorage.setItem('mi-duration',duration);localStorage.setItem('mi-reviewer',$('#reviewer').value);syncReviewer();$('#settings').close();render();toast('Impostazioni e approvatore salvati')};
setInterval(()=>{const d=new Date();$('#clock').textContent=d.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});$('#countdown').textContent='00:'+String(Math.max(seconds,0)).padStart(2,'0')},1000);setInterval(tick,1000);$('#department').value=localStorage.getItem('mi-department')||"Tutta l'azienda";savePending();render();
